# Generated by cpputils-cmake.
include /home/data/user_bkup/study/shenlan/sefr/ICP/build/CMakeFiles/icp.dir/flags.make
.PHONY: check-syntax
check-syntax:
	${CXX} -o /dev/null ${CXX_FLAGS} ${CXX_DEFINES} ${CXX_INCLUDES}  -S ${CHK_SOURCES}